name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Calculate SHA256 checksum
        id: calculate_sha256
        run: |
          curl -L -o saml-auth-${{ github.event.inputs.version }}.tar.gz https://github.com/FathAllaTechOps/saml-auth/archive/${{ github.event.inputs.version }}.tar.gz
          shasum -a 256 saml-auth-${{ github.event.inputs.version }}.tar.gz

      # - name: Update Homebrew formula
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: saml-auth-sha256
      #     path: sha256.txt

      # - name: Checkout Homebrew formula repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: FathAllaTechOps/homebrew-saml-auth
      #     ref: main

      # - name: Push updated formula to Homebrew repository
      #   run: |
      #     #new_version="${{ github.event.inputs.version }}"
      #     #tree
      #     # Update the URL
      #     #sed -i '' "s/url \".*\"/url \"https:\/\/github.com\/FathAllaTechOps\/saml-auth\/archive\/$new_version.tar.gz\"/g" Formula/saml-auth.rb

      #     # Update the version in the formula
      #     #sed -i '' "s/version .*/version \"$new_version\"/g" Formula/saml-auth.rb

      #     # Update the SHA 
      #     sed -i '' "s/sha256 .*/sha256 \"${{ steps.calculate_sha256.outputs.sha256 }}\"/g" Formula/saml-auth.rb

      #     git add Formula/saml-auth.rb
      #     git commit -m "Update saml-auth formula to version ${{ github.event.inputs.version }}"
      #     git push origin main
